apiVersion: cache.custom.k8s.io/v1alpha1
kind: Memcached
metadata:
  labels:
    app.kubernetes.io/name: memcached
    app.kubernetes.io/instance: memcached-sample
    app.kubernetes.io/part-of: k8soperator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8soperator
  name: memcached-sample
spec:
  # TODO(user): Add fields here
